services:
  students-create-service:
    build: .
    container_name: students-create-service
    ports:
      - "8082:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    networks:
      - mongo-network
networks:
  mongo-network:
    external: true
    name: mongo-network

